import React from 'react';

export interface EvidenceLog {
  evidence_id?: string;
  category?: string;
  from_user_name?: string;
  to_user_name?: string;
  event_type?: string;
  location?: string;
  seal_number?: string;
  condition?: string;
  notes?: string;
  photo?: string | null;
  signature?: string | null;
  timestamp?: string;
}

interface EvidenceReportModalProps {
  evidenceId: string;
  logs: EvidenceLog[] | any[];
  onClose: () => void;
}

export default function EvidenceReportModal({ evidenceId, logs, onClose }: EvidenceReportModalProps) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white text-gray-900 rounded-lg max-w-3xl w-full p-6 space-y-4 shadow-2xl overflow-y-auto max-h-[90vh] print:max-h-none print:shadow-none print:w-full print:p-0 print:absolute print:inset-0">
        
        {/* Header & Controls */}
        <div className="flex justify-between items-center border-b pb-4">
          <div>
            <h2 className="text-xl font-bold tracking-tight text-gray-900">ELECTRONIC CHAIN OF CUSTODY REPORT</h2>
            <p className="text-xs text-gray-600 font-mono mt-1">
              Evidence ID: <span className="font-bold text-blue-700">{evidenceId || 'N/A'}</span>
            </p>
          </div>

          {/* Action Buttons (Hidden during active print) */}
          <div className="print:hidden flex gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold px-4 py-2 rounded transition"
            >
              🖨️ Print / Save as PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              className="bg-gray-200 hover:bg-gray-300 text-gray-800 text-xs font-semibold px-3 py-2 rounded transition"
            >
              ✕ Close
            </button>
          </div>
        </div>

        {/* Audit Meta Details */}
        <div className="grid grid-cols-2 gap-4 text-xs bg-gray-50 p-3 rounded border">
          <div>
            <p className="text-gray-500">Report Generated:</p>
            <p className="font-semibold">{new Date().toLocaleString()}</p>
          </div>
          <div>
            <p className="text-gray-500">Total Audit Entries:</p>
            <p className="font-semibold">{logs.length}</p>
          </div>
        </div>

        {/* Audit Trail Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-100 border-b border-gray-300 font-semibold text-gray-700">
                <th className="p-2 border border-gray-300">Date/Time</th>
                <th className="p-2 border border-gray-300">Event / Action</th>
                <th className="p-2 border border-gray-300">Custodians (From ➔ To)</th>
                <th className="p-2 border border-gray-300">Location & Seal Tag</th>
              </tr>
            </thead>
            <tbody>
              {logs.length > 0 ? (
                logs.map((log, index) => (
                  <tr key={index} className="border-b border-gray-200">
                    <td className="p-2 border border-gray-300 font-mono">{log.timestamp || new Date().toLocaleString()}</td>
                    <td className="p-2 border border-gray-300">{log.event_type || 'Transfer'}</td>
                    <td className="p-2 border border-gray-300">
                      {log.from_user_name || 'System'} ➔ <strong>{log.to_user_name || 'Unassigned'}</strong>
                    </td>
                    <td className="p-2 border border-gray-300">
                      <div>{log.location || 'N/A'}</div>
                      <div className="text-[10px] text-gray-500">Seal Tag: {log.seal_number || 'N/A'}</div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={4} className="p-4 text-center text-gray-500 italic">
                    No active custody entries logged for this ID.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Legal Certification Footer */}
        <div className="pt-4 border-t border-gray-200">
          <p className="text-[10px] text-gray-500 italic">
            This document serves as an immutable Electronic Chain of Custody (E-COC) forensic record generated by the system.
          </p>
        </div>

      </div>
    </div>
  );
}